spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mptest?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  #mapper-locations: classpath*:mapper.springbootmybatisplus/*.xml
  #  MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，
  #注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  #  typeAliasesPackage: cn.tqktqk.spring.springbootmybatisplus.entity
  # 与 typeAliasesPackage 一起使用，仅扫描以该类作为父类的类
  # type-aliases-super-type: java.lang.Object
  # 配置扫描通用枚举,配置该属性，会对枚举类进行注入
  #  typeEnumsPackage:
  # 该包下的类注册为自定义类型转换处理类，用于属性类型转换
  # type-handlers-package:
  # 指定 mybatis 处理器
  # executorType: simple
  configuration:
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #      # 配置表明前缀，例如表设计时表名为tb_manager，对应entity为Manager
      #      table-prefix: mp_
      #逻辑已删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
    # 是否开启like查询，即对 stirng 字段是否使用 like，默认不开启
    # column-like: false
logging:
  level:
    # 日志级别，显示操作sql
    cn.tqktqk.spring.springbootmybatisplus.dao: debug